import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export async function getServerSideProps(){
  const response = await fetch('http://localhost:8000').then(x => x.json())
  return{
    props: {
      status: response.status,
    }
  }
}

export default function Home({status}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Welcome to Nextjs</h1>
          <div>Status is : {status}</div>
        </div>
      </main>
    </>
  )
}
